docs/TESTS.md
Same as https://github.com/exercism/java/pull/1505 ;-)
=> Reflect Apple's OS rebranding

.travis.yml, docs/SNIPPET.txt, exercises/calculator-service/.meta/reference/calculator_service.bal, exercises/calculator-service/calculator_service.bal, exercises/calculator-service/test/calclulator_service_test.bal, exercises/echo-service/.meta/reference/echo_service.bal, exercises/greeting-service/.meta/reference/greeting_service.bal, exercises/legacy-service-client/tests/legacy_quote_service.bal, exercises/order-management/.meta/reference/order_mgt.bal, exercises/order-management/test/order_mgt_test.bal, exercises/service-composition/.meta/reference/travel_agency_service.bal, exercises/service-composition/test/airline_reservation_service.bal, exercises/service-composition/test/car_rental_service.bal, exercises/service-composition/test/hotel_reservation_service.bal, exercises/service-invocation/.meta/reference/inovker_service.bal, exercises/service-invocation/test/quote_service.bal
=> Update exercises for 0.991.0 distribution

exercises/service-invocation/test/invoker_service_test.bal, exercises/service-invocation/test/quote_service.bal
As a response to https://exercism.io/mentor/solutions/f5b65e658d0f46939f8808b1c873072e#discussion-post-363045
=> Improve service invocation exercise test case

docs/INSTALLATION.md
New: https://ballerina.io/learn/installing-ballerina/
Broken: https://ballerina.io/learn/getting-started/
=> Update broken link in INSTALLATION.md

docs/LEARNING.md
This is to fix the links in the LEARNING.md file of the Ballerina track.
=> Fix Links in Learning Ballerina

config/maintainers.json
In an email, kasun04 indicated no longer having time to be a maintainer.
=> maintainers: make kasun04 an alumnus

config/maintainers.json
This is to remove the members bearing the below GitHub IDs:
1. Manuri
2. Kasun
Also, to add the members bearing the below GitHub IDs:
1. praneesha
2. bhashinee
4. pubudu91
5. daneshk
6. irshadnilam
7. chamil321
=> Add New Members and Remove Old Members

exercises/practice/hello-world/hello_world.bal
Simplify the `hello-world` exercise's stub. The goal of this is to make things easier for students to get started and to introduce as little syntax as possible.
See https://github.com/exercism/v3-launch/issues/46
=> 🤖 Simplify `hello-world` stub

config.json
The tests are timing out for a majority of the exercises. I am hoping this fixes it.
=> Increase average run time

docs/INSTALLATION.md, docs/RESOURCES.md, docs/TESTS.md
- docs/TESTS.md: same commands were repeated three times.
- docs/RESOURCES.md: populate from exercises/shared/.docs/help.md
- docs/INSTALLATION.md: broken link
=> Fix some broken links, and streamline docs

exercises/practice/basics-transformation-csv/.docs/instructions.md, exercises/practice/basics-transformation-json/.docs/instructions.md, exercises/practice/basics-transformation-xml/.docs/instructions.md, exercises/practice/database-employee-onboarding/.docs/instructions.md, exercises/practice/database-large-expenses/.docs/instructions.md, exercises/practice/service-composition/tests/travel_agency_service_test.bal, exercises/practice/service-composition/travel_agency_service.bal
- Fixes broken links in XML Fuel Allowance, JSON Fuel Allowance, CSV Fuel Allowance, Database Large Expenses, Service Composition and Employee Onboarding problems
- Enables test cases and fixes typo in Service Composition problem
=> Update ballerina exercism problems

exercises/practice/hello-world-service/hello_world_service.bal
$subject by improving comments and formatting
=> Improve hello-world-service exercise

docs/SNIPPET.txt
Update the `SNIPPET.txt` file to update the latest syntax of Ballerina in its code.
=> Update `SNIPPET.txt` to update latest syntax

exercises/practice/echo-service/echo_service.bal
Improve sample code by applying correct indentation. 
Note: The source code has been manually formatted to improve readability.
=> Format sample code

config.json
Add a `Key features` section to Ballerina track
=> Add a `Key features` section to Ballerina track

docs/INSTALLATION.md, docs/LEARNING.md, docs/RESOURCES.md
Update docs of Ballerina track
=> Update docs of Ballerina track

docs/TESTS.md
Review and update the testing doc page.
=> Review and update the testing doc page

config.json, exercises/practice/http-cake-is-a-lie/.meta/reference/main.bal, exercises/practice/http-cake-is-a-lie/main.bal
$subject 
1. Improve sample code
2. Improve solution
3. Make the exercise active
=> Improve cake-is-a-lie exercise

exercises/practice/http-cake-is-a-lie/.meta/reference/main.bal, exercises/practice/http-cake-is-a-lie/Dependencies.toml, exercises/practice/http-cake-is-a-lie/main.bal
=> Remove isolated vars from cake-is-a-lie exercise

exercises/practice/http-cake-is-a-lie/main.bal
=> Improve sample code of cake-is-a-lie exercise

exercises/practice/service-composition/travel_agency_service.bal
$subject to specify the endpoints of the services.
=> Improve instructions of Service Composition exercise

exercises/practice/service-composition/Ballerina.toml
=> Updater service composition example dist version

config.json
Closes https://github.com/exercism/ballerina/issues/105
=> Set highlightjs language to ballerina

config.json, exercises/practice/acronym/.meta/config.json, exercises/practice/binary-search/.meta/config.json, exercises/practice/bob/.meta/config.json, exercises/practice/http-salary-converter/.meta/config.json, exercises/practice/saddle-points/.meta/config.json
The results of running `configlet fmt`
=> Format config files

exercises/practice/rna-transcription/rna_transcription.bal
=> Remove example code from `rna-transcription` stub
